name: Visual Regression Test

on:
  - push
  - pull_request

jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: get-version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-version.outputs.node }}
      - run: npm install
      - run: |
          npm run build-storybook
          npx -y storycap --serverCmd 'npx http-server storybook-static -p 6007' http://localhost:6007
      - uses: reg-viz/reg-actions@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-directory-path: __screenshots__
          outdated-comment-action: minimize
          comment-report-format: summarized
