name: VRT

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "node=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: get-version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-version.outputs.node }}
      - run: npm ci
      - run: npm run vrt
      - run: |
          git add -N test
          if ! git diff --exit-code --quiet test
          then
            git config user.name  "GitHub Action"
            git config user.email "action@github.com"
            git add test
            git commit -m "Update screenshots [ci skip]"
            git push origin HEAD:${{ github.head_ref }}
          fi
