name: VRT

on:
  pull_request:
    types:
      - opened
      - synchronize
  # for cache
  push:
    branches:
      - main
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        id: vars
        run: |
          echo "node_version=$(cat .node-version)" >> $GITHUB_OUTPUT
          echo "cache_key=${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT
          echo "playwright_version=$(cat package-lock.json | grep -m1 -E 'playwright.*"[0-9]+\.[0-9]+\.[0-9]+"' | sed -E 's|.*([0-9]+\.[0-9]+\.[0-9]+).*|\1|')" >> $GITHUB_OUTPUT
      - name: a
        uses: namikingsoft/vrt-workflows-2024@workflow-dispatch-using-github-app
        with:
          node_version: ${{ steps.vars.outputs.node_version }}
          playwright_image_tag: v${{ steps.vars.outputs.playwright_version }}
          install_command: npm ci
          snapshots_command: npm run snapshot --
          snapshots_dirpath: test/vrt.e2e.ts-snapshots
          shard_count: 2
          cache_key: vrt-${{ steps.vars.outputs.cache_key }}
          cache_paths: node_modules
          force_update_base_snapshots: false
