name: VRT

on:
  pull_request:
    types:
      - opened
      - synchronize
  # for cache
  push:
    branches:
      - main
      - master

jobs:
  vrt:
    uses: namikingsoft/vrt-workflows-2024/.github/workflows/snapshots.yml@main
    with:
      vrt_repo: namikingsoft/vrt-workflows-2024
      snapshots_command: npm run snapshot
      snapshots_dirpath: test/vrt.e2e.ts-snapshots
    secrets:
      your_repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      vrt_repo_github_token: ${{ secrets.VRT_DIFF_GITHUB_TOKEN }}
